FROM golang:1.25-trixie

RUN apt-get update \
	&& apt-get install -y --no-install-recommends curl ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download -x 2>&1 | tail -3

COPY . .

CMD ["go", "test", "./..."]
