// Mock window.app for tests
window.app = {
  config: {
    siteRoot: '/',
    loginUrl: '/login',
    avatarInfo: {},
    logoPath: '/logo.png',
    mediaUrl: '/media/',
    siteTitle: 'SesameFS',
    siteName: 'SesameFS',
    logoWidth: 100,
    logoHeight: 40,
    isPro: 'True',
    isDBSqlite3: false,
    isDocs: 'False',
    lang: 'en',
    fileServerRoot: '/seafhttp/',
    useGoFileserver: true,
    seafileVersion: '9.0.0',
    serviceURL: 'http://localhost:8000',
    avatarURL: '/avatars/',
    faviconPath: '/favicon.ico',
    loginBGPath: '/login-bg.png',
    enableRepoAutoDel: false,
  },
  pageOptions: {
    trashReposExpireDays: 30,
    seafileCollabServer: '',
    name: 'Test User',
    contactEmail: 'test@example.com',
    username: 'test@example.com',
    canAddRepo: true,
    canShareRepo: true,
    canAddGroup: true,
    groupImportMembersExtraMsg: '',
    canGenerateShareLink: true,
    canGenerateUploadLink: true,
    canSendShareLinkEmail: true,
    canViewOrg: 'False',
    fileAuditEnabled: false,
    folderPermEnabled: false,
    enableResetEncryptedRepoPassword: 'False',
    isEmailConfigured: 'True',
    enableUploadFolder: 'True',
    enableResumableFileUpload: 'True',
    resumableUploadFileBlockSize: 8,
    resumableSimultaneousUploads: 1,
    storages: [],
    libraryTemplates: [],
    enableRepoSnapshotLabel: false,
    shareLinkForceUsePassword: false,
    shareLinkPasswordMinLength: 4,
    shareLinkPasswordStrengthLevel: 1,
    shareLinkExpireDaysMin: 0,
    shareLinkExpireDaysMax: 0,
    shareLinkExpireDaysDefault: 0,
    sideNavFooterCustomHtml: '',
    aboutDialogCustomHtml: '',
    uploadLinkExpireDaysMin: 0,
    enableShareToDepartment: false,
    maxFileName: 255,
    canPublishRepo: false,
    enableEncryptedLibrary: true,
    enableRepoHistorySetting: true,
    isSystemStaff: false,
    thumbnailSizeForOriginal: 1024,
    repoPasswordMinLength: 8,
    canAddPublicRepo: false,
    canLockUnlockFile: true,
    customNavItems: [],
    enableShowContactEmailWhenSearchUser: false,
    enableShowLoginIDWhenSearchUser: false,
    maxUploadFileSize: 20480,
    maxNumberOfFilesForFileupload: 1000,
    enableOCM: false,
    ocmRemoteServers: [],
    enableOCMViaWebdav: false,
    enableSSOToThirdpartWebsite: false,
    enableSeadoc: false,
    curNoteMsg: '',
    curNoteID: '',
    enableTC: false,
    enableVideoThumbnail: false,
    enableThumbnail: false,
    enableOnlyoffice: false,
    onlyofficeConverterExtensions: [],
    canSetExProps: false,
    enableSeafileAI: false,
    workspaceID: '',
    showLogoutIcon: true,
    additionalShareDialogNote: '',
    additionalAppBottomLinks: [],
    additionalAboutDialogLinks: [],
    enableSeaTableIntegration: false,
    userRole: 'default',
  },
};

// Mock gettext
window.gettext = (text) => text;

// Mock ResizeObserver
class ResizeObserver {
  observe() { }
  unobserve() { }
  disconnect() { }
}
window.ResizeObserver = ResizeObserver;
