import { gettext } from './utils/constants';

gettext('You have not shared any folders');
gettext('You don\'t have any share links');
gettext('You don\'t have any upload links');
gettext('You don\'t have any favorite items yet');
gettext('Modify');
gettext('Import Users');
gettext('No connected devices');
gettext('No sync errors');
gettext('No groups');
gettext('No notifications');
gettext('Notification Detail');
gettext('No share links');
gettext('No upload links');
gettext('No terms and conditions');
gettext('Deleted users remain restorable for up to {placeholder} days after deletion before permanent cleanup.');
gettext('Deleted users are cleaned up according to the current system retention policy.');
gettext('Deleted organizations remain restorable for up to {placeholder} days after deletion before permanent cleanup.');
gettext('Deleted organizations are cleaned up according to the current system retention policy.');
gettext('You have not deleted any libraries in the last {placeholder} days. A deleted library will be cleaned automatically after this period.');
gettext('Deleted libraries are kept in trash for {placeholder} days before automatic cleanup.');
gettext('Tip: libraries deleted {trashReposExpireDays} days ago will be cleaned automatically.');
gettext('You have not deleted any libraries recently. Deleted libraries are cleaned automatically according to the current system retention policy.');
gettext('Tip: deleted libraries are cleaned automatically according to the current system retention policy.');
gettext('Retention policy');
gettext('Deleted organizations');
gettext('User grace window');
gettext('Org grace window');
gettext('Library trash retention');
gettext('No favorites');
gettext('No folders shared');
gettext('No Admin login logs');
gettext('No Admin operation logs');
gettext('No permission logs');
gettext('No login logs');
gettext('No file update logs');
gettext('No file access logs');
gettext('Save Selected Items');
